CREATE TABLE EMPLOYEE (
   ID             BIGINT        NOT NULL PRIMARY KEY,
   FIRST_NAME     VARCHAR (30)  NOT NULL,
   LAST_NAME      VARCHAR (30)  NOT NULL
);

INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Bob', 'Smith');
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Jane', 'Doe');
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Sally', 'Ann');